### ISSUE TITLE
changing port 3000

### ISSUE THREAD

**Issue by pontusvision** [tomyitav/apollo-typed-lambda#164]
Hi, congrats on the great project; I'm trying to run it locally, but need to change the default port from 3000 to something else; can you please improve the readme to specify which config file should be changed to use a port other than 3000?

**Comment by tomyitav** [comment]
Hi @pontusvision , thanks for reaching out!
You can change the port by editing the ```start``` script in package.json file.
Pass the --port parameter to the sls offline command to set the port you want. Hope it helps! :-)
